-- Run this file in the Supabase SQL Editor for an existing people table.
-- Every successful INSERT, UPDATE, and DELETE is recorded transactionally.

create table if not exists public.people_history (
  id bigint generated by default as identity primary key,
  people_id bigint not null,
  person_name text,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  old_data jsonb,
  new_data jsonb,
  changed_at timestamptz not null default now()
);

alter table public.people_history add column if not exists person_name text;
update public.people_history
set person_name = coalesce(new_data ->> 'name', old_data ->> 'name')
where person_name is null;
alter table public.people_history alter column person_name set not null;

create index if not exists people_history_people_id_idx
  on public.people_history (people_id);
create index if not exists people_history_person_name_idx
  on public.people_history (person_name);
create index if not exists people_history_changed_at_idx
  on public.people_history (changed_at desc);

create or replace function public.write_people_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.people_history (people_id, person_name, action, old_data, new_data)
    values (new.id, new.name, 'INSERT', null, to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    if old.name is distinct from new.name then
      update public.people_history
      set person_name = new.name
      where people_id = new.id;
    end if;
    insert into public.people_history (people_id, person_name, action, old_data, new_data)
    values (new.id, new.name, 'UPDATE', to_jsonb(old), to_jsonb(new));
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.people_history (people_id, person_name, action, old_data, new_data)
    values (old.id, old.name, 'DELETE', to_jsonb(old), null);
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists people_write_history on public.people;
create trigger people_write_history
after insert or update or delete on public.people
for each row execute function public.write_people_history();

alter table public.people_history enable row level security;
drop policy if exists "anon select people history" on public.people_history;
create policy "anon select people history"
on public.people_history for select to anon using (true);

notify pgrst, 'reload schema';

-- Verification query:
-- select id, people_id, person_name, action, old_data, new_data, changed_at
-- from public.people_history
-- order by changed_at desc;
