create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  company text not null default '',
  department text not null default '',
  position text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists people_set_updated_at on public.people;
create trigger people_set_updated_at before update on public.people
for each row execute function public.set_updated_at();

alter table public.people enable row level security;
drop policy if exists "anon select people" on public.people;
drop policy if exists "anon insert people" on public.people;
drop policy if exists "anon update people" on public.people;
drop policy if exists "anon delete people" on public.people;
create policy "anon select people" on public.people for select to anon using (true);
create policy "anon insert people" on public.people for insert to anon with check (true);
create policy "anon update people" on public.people for update to anon using (true) with check (true);
create policy "anon delete people" on public.people for delete to anon using (true);

notify pgrst, 'reload schema';
