"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Person={id:number;name:string;company:string;department:string;position:string;created_at:string;updated_at:string};
type HistoryRow={id:number;people_id:number;person_name:string;action:"INSERT"|"UPDATE"|"DELETE";old_data:Person|null;new_data:Person|null;changed_at:string};
type Form=Pick<Person,"name"|"company"|"department"|"position">;
type ChartType="position"|"company"|"department";
const blank:Form={name:"",company:"",department:"",position:""};

export default function Home(){
 const [people,setPeople]=useState<Person[]>([]),[query,setQuery]=useState(""),[form,setForm]=useState<Form>(blank),[editing,setEditing]=useState<number|null>(null),[modal,setModal]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false),[message,setMessage]=useState(""),[historyPerson,setHistoryPerson]=useState<Person|null>(null),[historyRows,setHistoryRows]=useState<HistoryRow[]>([]),[historyLoading,setHistoryLoading]=useState(false),[historyError,setHistoryError]=useState(""),[chartType,setChartType]=useState<ChartType|null>(null);
 async function load(){setLoading(true);const response=await fetch("/api/people",{cache:"no-store"});const result=await response.json();if(!response.ok)setMessage(`목록을 불러오지 못했습니다: ${result.error}`);else{setMessage("");setPeople(result as Person[])}setLoading(false)}
 useEffect(()=>{void load()},[]);
 const shown=useMemo(()=>{const q=query.toLowerCase().trim();return people.filter(p=>!q||[p.name,p.company,p.department,p.position].some(v=>v.toLowerCase().includes(q)))},[people,query]);
 const chart=useMemo(()=>{const colors=["#4361ee","#14b8a6","#f59e0b","#ef476f","#8b5cf6","#0ea5e9","#84cc16","#f97316"];const field=chartType??"position";const counts=new Map<string,number>();people.forEach(p=>{const label=p[field].trim()||"미지정";counts.set(label,(counts.get(label)??0)+1)});let angleCursor=0;const items=Array.from(counts.entries()).sort((a,b)=>b[1]-a[1]).map(([label,count],index)=>{const percentage=people.length?count/people.length*100:0;const start=angleCursor;angleCursor+=percentage;return {label,count,color:colors[index%colors.length],percentage,labelAngle:(start+angleCursor)/2*3.6-102}});let cursor=0;const segments=items.map(item=>{const start=cursor;cursor+=item.percentage;return `${item.color} ${start}% ${cursor}%`});return {items,gradient:segments.length?`conic-gradient(${segments.join(",")})`:"conic-gradient(#e5e9f0 0 100%)"}},[people,chartType]);
 const chartMeta=chartType==="company"?{title:"회사별 인원 현황",description:"회사",unit:"명"}:chartType==="department"?{title:"부서별 인원 현황",description:"부서",unit:"명"}:{title:"직책별 인원 현황",description:"직책",unit:"명"};
 const create=()=>{setEditing(null);setForm(blank);setModal(true)};
 const edit=(p:Person)=>{setEditing(p.id);setForm({name:p.name,company:p.company,department:p.department,position:p.position});setModal(true)};
 async function openHistory(p:Person){setHistoryPerson(p);setHistoryRows([]);setHistoryError("");setHistoryLoading(true);try{const response=await fetch(`/api/people/history?name=${encodeURIComponent(p.name)}&peopleId=${p.id}`,{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error);setHistoryRows(result as HistoryRow[])}catch(error){setHistoryError(error instanceof Error?error.message:"히스토리를 불러오지 못했습니다.")}finally{setHistoryLoading(false)}}
 const closeHistory=()=>{setHistoryPerson(null);setHistoryRows([]);setHistoryError("")};
 const close=()=>{setModal(false);setEditing(null)};
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const response=await fetch(editing===null?"/api/people":`/api/people?id=${editing}`,{method:editing===null?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const result=await response.json();setSaving(false);if(!response.ok){setMessage(`저장하지 못했습니다: ${result.error}`);return}close();await load()}
 async function remove(p:Person){if(!confirm(`${p.name} 님을 삭제하시겠습니까?`))return;const response=await fetch(`/api/people?id=${p.id}`,{method:"DELETE"});const result=await response.json();if(!response.ok)setMessage(`삭제하지 못했습니다: ${result.error}`);else await load()}
 async function exportExcel(){setExporting(true);setMessage("");try{const response=await fetch(`/api/people/export?q=${encodeURIComponent(query)}`);if(!response.ok){const result=await response.json();throw new Error(result.error)}const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`people-${new Date().toISOString().slice(0,10)}.xlsx`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(error){setMessage(`엑셀 다운로드에 실패했습니다: ${error instanceof Error?error.message:"알 수 없는 오류"}`)}finally{setExporting(false)}}
 return <main className="shell">
  <aside><div className="brand"><b>P</b> People Manager</div><button className="nav">♙　인명 관리</button><div className="account"><i>관</i><span><strong>관리자</strong><small>Supabase 연결</small></span></div></aside>
  <section className="content"><header><div><h1>인명 관리</h1><p>회사 구성원 정보를 한곳에서 관리하세요.</p></div><button className="primary" onClick={create}>＋ 신규 등록</button></header>
   {message&&<div className="notice error">{message}</div>}
   <div className="stats"><article><span>전체 인원</span><button className="statNumberButton" type="button" onClick={()=>setChartType("position")} aria-label="직책별 인원 그래프 보기"><strong>{people.length}</strong></button> 명</article><article><span>회사</span><button className="statNumberButton" type="button" onClick={()=>setChartType("company")} aria-label="회사별 인원 그래프 보기"><strong>{new Set(people.map(p=>p.company)).size}</strong></button> 개</article><article><span>부서</span><button className="statNumberButton" type="button" onClick={()=>setChartType("department")} aria-label="부서별 인원 그래프 보기"><strong>{new Set(people.map(p=>p.department)).size}</strong></button> 개</article></div>
   <div className="panel"><div className="toolbar"><div><h2>인명 목록</h2><span>총 {shown.length}명</span></div><div className="toolbarActions"><label className="search">⌕<input aria-label="인명 검색" placeholder="이름, 회사, 부서, 직책 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="excelButton" onClick={()=>void exportExcel()} disabled={exporting}>{exporting?"생성 중...":"엑셀"}</button></div></div><div className="table"><table><thead><tr><th>이름</th><th>회사</th><th>부서</th><th>직책</th><th>등록일</th><th/></tr></thead><tbody>
    {shown.map(p=><tr key={p.id}><td><div className="person"><i>{p.name[0]}</i><span><button className="nameLink" onClick={()=>void openHistory(p)}>{p.name}</button></span></div></td><td>{p.company}</td><td>{p.department}</td><td><b className="badge">{p.position}</b></td><td>{new Date(p.created_at).toLocaleDateString("ko-KR")}</td><td className="actions"><button onClick={()=>edit(p)}>수정</button><button className="delete" onClick={()=>void remove(p)}>삭제</button></td></tr>)}
    {loading&&<tr><td colSpan={6} className="empty">목록을 불러오는 중입니다...</td></tr>}{!loading&&!shown.length&&<tr><td colSpan={6} className="empty">등록된 인명이 없습니다.</td></tr>}
   </tbody></table></div></div>
  </section>
  {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={save}><div className="modalHead"><div><h2>{editing===null?"신규 인명 등록":"인명 정보 수정"}</h2><p>회사와 소속 정보를 입력하세요.</p></div><button type="button" onClick={close}>×</button></div><div className="fields">
   <label>이름<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="홍길동"/></label><label>회사<input required value={form.company} onChange={e=>setForm({...form,company:e.target.value})} placeholder="회사명"/></label><label>부서<input required value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="개발팀"/></label><label>직책<input required value={form.position} onChange={e=>setForm({...form,position:e.target.value})} placeholder="팀장"/></label>
  </div><footer><button type="button" onClick={close}>취소</button><button className="primary" disabled={saving}>{saving?"저장 중...":editing===null?"등록하기":"저장하기"}</button></footer></form></div>}
  {chartType&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setChartType(null)}><section className="modal chartModal" role="dialog" aria-modal="true" aria-label={chartMeta.title}><div className="modalHead"><div><h2>{chartMeta.title}</h2><p>전체 {people.length}명의 {chartMeta.description} 분포를 원형 그래프로 표시합니다.</p></div><button type="button" onClick={()=>setChartType(null)} aria-label="닫기">×</button></div><div className="chartBody">{people.length===0?<p className="chartEmpty">표시할 인원 데이터가 없습니다.</p>:<><div className="chartPieStage"><div className="pie3d" style={{background:chart.gradient}}><div className="pieCenter"><strong>{people.length}</strong><span>전체 인원</span></div></div><div className="pieLabels">{chart.items.map(item=><span key={item.label} style={{left:`${50+Math.cos(item.labelAngle*Math.PI/180)*34}%`,top:`${50+Math.sin(item.labelAngle*Math.PI/180)*22}%`}}>{item.percentage.toFixed(1)}%</span>)}</div></div><div className="chartLegend">{chart.items.map(item=><div className="legendItem" key={item.label}><i style={{background:item.color}}/><span>{item.label}</span><strong>{item.count}{chartMeta.unit}</strong></div>)}</div></>}</div><footer><button type="button" onClick={()=>setChartType(null)}>닫기</button></footer></section></div>}
  {historyPerson&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&closeHistory()}><section className="modal historyModal" role="dialog" aria-modal="true" aria-label={`${historyPerson.name} 변경 히스토리`}><div className="modalHead"><div><h2>{historyPerson.name} 변경 히스토리</h2><p>히스토리 테이블에 저장된 데이터를 최신순으로 표시합니다.</p></div><button type="button" onClick={closeHistory} aria-label="닫기">×</button></div><div className="historyBody">{historyLoading&&<p className="historyEmpty">히스토리를 불러오는 중입니다...</p>}{historyError&&<div className="notice error">{historyError}</div>}{!historyLoading&&!historyError&&!historyRows.length&&<p className="historyEmpty">저장된 히스토리가 없습니다.</p>}{!historyLoading&&!historyError&&historyRows.length>0&&<div className="historyTableWrap"><table className="historyTable"><thead><tr><th>이름</th><th>회사</th><th>부서</th><th>직책</th><th>등록일</th></tr></thead><tbody>{historyRows.map(row=>{const data=row.new_data??row.old_data;return <tr key={row.id}><td><strong>{data?.name??row.person_name}</strong><small><b className={`historyAction ${row.action.toLowerCase()}`}>{row.action==="INSERT"?"신규":row.action==="UPDATE"?"수정":"삭제"}</b>{new Date(row.changed_at).toLocaleString("ko-KR")}</small></td><td>{data?.company??"-"}</td><td>{data?.department??"-"}</td><td>{data?.position??"-"}</td><td>{data?.created_at?new Date(data.created_at).toLocaleDateString("ko-KR"):"-"}</td></tr>})}</tbody></table></div>}</div><footer><button type="button" onClick={closeHistory}>닫기</button></footer></section></div>}
 </main>
}

